// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afycwwqygqsnjskcnchr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmeWN3d3F5Z3Fzbmpza2NuY2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjIzNTcsImV4cCI6MjA3MDQzODM1N30.HeXjx3tVSii8fHw0PS9x1cCZ36IbVIehUk5zsvI_tig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});